### ISSUE TITLE
Proposal peer review-Diwali-Dhamaka

### ISSUE THREAD

**Issue by Peter-Yeh-coder** [INFO-526-S24/project-01-Crimson#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- [Peter Yeh] - @[Peter-Yeh-coder]
- [Miki Katyal] - @[Miki Katyal]
- [Anusha Nagaraja] - @[anusharaj1997]
- [Vidhyannth Sivashanmugam] - @[Vidhyananth Sivashanmugam]
- [gowtham theeda]-@[gowthamtheeda]
- [Kondapaneni Siva Rohit] -@[Sivarohitk]

- Describe the goal of the project.
The goal of this project is to determine the impact of the pandemic on company stock prices. The secondary question asks how much stock return is influenced by the day of the week and seasonality.

- Describe the data used or collected.
The data used is split into two .csv files. big_tech_stock_prices.csv and big_tech_companies.csv. The stock price data contains data about daily company stock prices and trading volume. The tech companies .csv contains the company names and the stock symbol.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The first question about the pandemic will use a line plot with the dates within the pandemic time period as the x-axis,  average returns as the y-axis, and differentiation of the top big tech companies facets/colors.

The second question plans to calculate the average of the high, low, and adjusted close for use in the analysis. The date will also be transformed into Weekday and other potential designations. The current plan is between a boxplot or line plot with facets and colors being used to differentiate companies and periods of interest.

- Is there anything that is unclear from the proposal?
How do define impact?
What do you mean by season?
How are you proving the causality of COVID-19 on stock prices instead of correlation?
How is the season being used for Question 2?
Are the weekday returns comparable within a season or a year?

- Provide constructive feedback on how the team might be able to improve their project.
Put the details of what kind of plot at the top of your approach and then detail the axis and facets afterward.
Since you are working with averages for the plots, you should label the axis accordingly.
Seasons and quarters are not equivalent, you should use quarter instead.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are most interested in the relationship between the pandemic and stock prices.

- Provide constructive feedback on any issues with file and/or code organization.
More code commentation would be nice to see so that we know the details of what is occurring.

- (Optional) Any further comments or feedback?

**Comment by ArunKoundinya** [comment]
Finished updates based on peer review based on the following fixes.

Fix #1 - Code comments are updated.
Fix #2 - Stock Price Impact of COVID-19 method is added.
Fix #3 - We are measuring based on financial quarters. Seasonality is removed.
Fix #4 - Since we only stock prices data we cannot find casulity. Only trends and returns can be observed. The same is kept as a note in proposal.
Fix #5 - Write-up alignment of plot details and then x-axis and y-axis are mentioned later.

Fix Not provided for "Are the weekday returns comparable within a season or a year?"
WeekDays Returns with quarters will checked in box plot or any other plots. Which is already mentioned in earlier write-up.
