### ISSUE TITLE
Proposal peer review from Team InsightSquad

### ISSUE THREAD

**Issue by vemuladevendran** [INFO-526-S24/project-01-Crimson#2]
The following is the peer review of the project proposal by InsightSquad. The team members that participated in this review are 

- Shreemithra Naveen - @shreemithran
- Gowtham - @Gowtham-18
- Mohammad Farmani - @mfarmani95
- Narasimha Vardhan Rachaputi - @nvrachaputi
- Amaan - @amaanam
- Devendran - @vemuladevendran

**- Describe the goal of the project.**

The project aims to analyze and visualize the impact of the pandemic on the stock prices of 14 big tech companies over a specified period. The team aims to answer two specific questions:

1.  Identify companies with the highest/lowest impact on their stock prices due to the pandemic,
2.  Explore patterns in returns on stock prices based on days of the week and seasonality.

**- Describe the data used or collected.**

 The Big Tech Stock Prices dataset. It consists of daily stock prices and trading volumes for 14 prominent technology companies, spanning nearly a decade. The dataset is well-structured, containing two tables: big_tech_stock_prices.csv and big_tech_companies.csv. 

**- Describe how the research question will be answered, e.g. what approaches/methods will be used.**

 Question 1: The team plans to identify the pandemic period starting from 2020 and calculate average returns, 3- and 5-year returns, and respective peak prices. Visualizations will use geom_line(), geom_col(), and annotations via geom_text() to show the impact on stock prices for different companies.

Question 2: For analyzing trends in stock prices, the team will explore weekdays and financial quarters. Utilizing day-wise data and adding a column for year and quarter, they will calculate averages for high, low, and adj_close during specified periods. Visualizations may involve geom_box() or geom_line() with facets and colors differentiating companies and periods

**- Is there anything unclear from the proposal?**

The proposal is clear and well-organized. However, it might be beneficial to elaborate on the specific criteria for determining the impact on stock prices during the pandemic and how the team plans to define and visualize these impacts.

**- Provide constructive feedback on how the team might be able to improve their project.**

Consider providing more details on the criteria for determining the impact on stock prices during the pandemic.

**- What aspect of this project are you most interested in and would like to see highlighted in the presentation.**

I am particularly interested in seeing the visualizations depicting the impact of the pandemic on stock prices for different big tech companies.

**- Provide constructive feedback on any issues with file and/or code organization.**

It's positive that the file and code organization are perceived as well-structured. The use of a code-summary section is indeed a good practice for providing a clear overview and explanation of the code

- (Optional) Any further comments or feedback?

**Comment by ArunKoundinya** [comment]
Finished updates based on peer review based on the following fixes.

Fix #1 - Stock Price Impact of COVID-19 method is added.
