### ISSUE TITLE
Presentation peer review-Diwali

### ISSUE THREAD

**Issue by Peter-Yeh-coder** [INFO-526-S24/project-01-Crimson#4]
The following is the peer review of the Presentation by Diwali. The team members that participated in this review are 

- Peter Yeh - @Peter-Yeh-coder

- Miki Katyal - @Miki Katyal

- Anusha Nagaraja - @anusharaj1997

- Vidhyannth Sivashanmugam - @Vidhyananth Sivashanmugam

- gowtham theeda-@gowthamtheeda

- Kondapaneni Siva Rohit -@Sivarohitk

- Content: Is the research question well designed and is the data being used relevant to the research question?

The research question appeared to be well-designed and the data used appeared to be relevant.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

The visualizations appeared to be appropriate and seemed to correlate with what they said.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

We do not recall about limitations being discussed.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

There is a lot of text for some plot slides, specifically detailing how they generated the plot. Slides with a lot of text were hard to read. Slides with the plot are a bit hard to take in due to the number of facets or overlayed lines. Plot 1 for question 1 has a lot of lines colored the same and no distinction between which line corresponded with which line. Question 1 Plot 3 looked a bit cut off.

Question 2 Plot 1 animation was too fast. Question 2 Plot 2 is hard to read due to the number of facets.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

It was well explained and seemed well practiced. Everyone seemed to say something meaningful.

**Comment by ArunKoundinya** [comment]
Feedback on the peer review comments:

1. Text and plots go hand in hand. I don't think there is a lot of text when there are a total of five different plots.
2. The same colors should be used in a line plot when there are different variables and has similar trend. Accordingly, two different colors are used to highlight a few companies. Additionally, text is used as an annotation to help non-data scientists takeaway learnings from plot 1.
3. Corrections for plot 3 will be made by adjusting the decimal to the tenth place and highlighting negative returns with a different color.

#fixes will be provided in next git commit.
