### ISSUE TITLE
 Presentation peer review from team InsightSquad

### ISSUE THREAD

**Issue by vemuladevendran** [INFO-526-S24/project-01-Crimson#5]
The following is the peer review of the Presentation proposal by InsightSquad. The team members that participated in this review are 

- Shreemithra Naveen - @shreemithran
- Gowtham - @Gowtham-18
- Mohammad Farmani - @mfarmani95
- Narasimha Vardhan Rachaputi - @nvrachaputi
- Amaan - @amaanam
- Devendran - @vemuladevendran

- Content: Is the research question well designed and is the data being used relevant to the research question?

Yes, their research question is clearly set up and fits the topic well.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Yes, the team selected appropriate visualizations

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

Yes, the project demonstrates careful planning and consideration, which is evident in the quality of their graphs and presentation. There's a clear sign of creativity in how they've presented their data. However, they haven't addressed potential limitations within their study, which would be a valuable addition to a comprehensive analysis.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

Yes, the slides seem to be well-structured, but they are somewhat text-heavy, which affects readability and comprehension. Regarding the visuals, the first plot appears cluttered, making it challenging to distinguish between the stock prices of the two companies featured.

The second plot includes an animation that progresses too quickly to allow the data to be adequately observed. 
Additionally, the use of faceting in another graph results in a congested display. 
Simplifying the content and adjusting the pacing and layout of these graphical elements would enhance the overall effectiveness of the presentation.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

The team presented quite well and showed that they had prepared and practiced. Each member had the chance to speak on significant aspects of the project, contributing valuable insights. Overall, the team gave a decent presentation.

**Comment by ArunKoundinya** [comment]
Feedback on the peer review comments:

1. Text and plots go hand in hand. I don't think there is a lot of text when there are a total of five different plots.
2. The same colors should be used in a line plot when there are different variables and has similar trend. Accordingly, two different colors are used to highlight a few companies. Additionally, text is used as an annotation to help non-data scientists takeaway learnings from plot 1.
3. Corrections for animated plot to slow down the animation pace will be looked and will try to provide the fix in next git commit.

#fixes will be provided in next git commit.
